### ISSUE TITLE
Client AP and Access Point Mode DNS not given to Clients

### ISSUE THREAD

**Issue by krachlatte** [fdivitto/ESPWebFramework#10]
Hi,

it looks like dns servers are not forwarded by DHCP to the client, when running in Client AP and Acesspoint mode.

let me know what you need

many thanks

**Comment by krachlatte** [comment]
only works wiht static assigned ip and dns servers

**Comment by krachlatte** [comment]
Requirements:
1. Devices connected to ESP8266 Access Point network needs to have DNS set manually (ie. 8.8.8.8 and 8.8.4.4)

**Comment by fdivitto** [comment]
Thank you for the report. I will investigate the source of this problem.

Fabrizio
