### ISSUE TITLE
Building from source:OK. But web interface doesn't respond!

### ISSUE THREAD

**Issue by mralexgray** [fdivitto/ESPWebFramework#11]
I revamped the makefile to work on a Mac.  The build goes very well.. [here is the complete output](https://gist.github.com/mralexgray/5f2cb1e67ffe2d0acb71).

However, it does not work (the web interface).

When I simply flash the checked out files, via..

`esptool.py --port /dev/tty.wchusbserialfd5320  write_flash 0x11000 app.out-0x11000.bin 0x00000 app.out-0x00000.bin 0x6C000 webcontent.bin`

everything comes up fine..

but on my built copy..  everything seems to work EXCEPT the web interface.  

I AM able to 
1. Join the wifi-AP station it creates.
2.  get an IP address.
3. pull up the console `❯ minicom -D /dev/cu.wchusbserialfd5320 -b 9600` -> `$`

I cannot get the pages to serve..

`❯ curl 192.168.4.1
curl: (56) Recv failure: Connection reset by peer`

in chrome..
`GET http://192.168.4.1/ net::ERR_CONNECTION_REFUSED`

<strike>The ONLY difference I can spot is...

factory bins...
`Wrote 33792 bytes at 0x0006c000 in 4.0 seconds (68.3 kbit/s)...`
mine..
`Wrote 31744 bytes at 0x0006c000 in 3.7 seconds (68.3 kbit/s)...`
</strike>
(Turns out it was just because of a different image I had slipped in there.. in actuality.  the size of the bins I am "making" end up EXACTLY the same size as yours!)

for the record, though.. My `python` is.. `Python 2.7.10` (Mac OS X, obviously)

Any advice?

ps: Let me know if you want me to push the makefile revisions that enabled cross-platform compilation. :-)

**Comment by fdivitto** [comment]
Thank you for the tests, I'll investigate it very soon.
However I have two questions:

1) have you tried to compile using last commit (the today one)?
2) does it works using the pre-compiled binaries?

Cheers,
Fabrizio
