### ISSUE TITLE
Align file structure to better match best practices.

### ISSUE THREAD

**Issue by mralexgray** [fdivitto/ESPWebFramework#19]
This is a drastically revised project structure.. but is much more in-line with other projects and will be easier to maintain in the long run. <strike>This may break some things because doing it amidst you doing other changes was hard to keep the branches in sync. If anything doesn't work, it can be easily fixed. </strike>  It's working fine.

@fdivitto, let me know if you are hesitant, i can elaborate further why it's nice to stick to what people know/expect, even if kind of scary moving things around so drastically.

![screen shot 2016-01-27 at 6 16 30 pm](https://cloud.githubusercontent.com/assets/262517/12631889/1cde0fb8-c522-11e5-9b3d-9645390a93bd.png)

**Comment by fdivitto** [comment]
Something done...
