### ISSUE TITLE
nodemcu flasher???

### ISSUE THREAD

**Issue by aryan2013** [fdivitto/ESPWebFramework#5]
Can i use nodeMCU flasher for flashing bin file to specified address using configuration tab of nodeMCU flasher?

I did so and found flashing ok, but after removing GPIO0 and rebooting, i am not able to search my ESP-01 as wifi Access Point in mobile or laptop.

**Comment by aryan2013** [comment]
Sorry, i think nodeMCU flasher will not work.. I tried python and it is working fine.

Hey fdivitto,  you made this chip awesome....Hat's off to you!

**Comment by tomasmcm** [comment]
Actually I couldn't flash the board with the python script it kept saying I didn't had serial module. And I tried with nodeMCU flasher and it worked first time! You just have to set the address to the 3 files and the correct address code on the right, also don't forget to check the cross for each file (otherwise they will be ignored).
By the way, amazing work!

**Comment by fdivitto** [comment]
Hello, many thanks for the suggestions.
What do you actually mean when you write "You just have to set the address to the 3 files and the correct address code on the right, also don't forget to check the cross for each file (otherwise they will be ignored)"?

Regards,
Fabrizio

**Comment by tomasmcm** [comment]
On the config tab you can select the files to flash onto the board. If you press the clog you can set the file system address, next to the clog you can set the offset address for the files (0x40000, 0x00000 and 0x17000), finally you need to check the box on left of each file to mark them for flashing.
Hope it helps

![687474703a2f2f693635392e70686f746f6275636b65742e636f6d2f616c62756d732f75753331362f766f77737461722f4e6f64654d43552d466c61736865722d53657474696e672e706e67](https://cloud.githubusercontent.com/assets/6323928/9744755/a504d48e-5665-11e5-9b75-e4bddc56023a.png)

**Comment by fdivitto** [comment]
Thank you!
However having installed python 2.7 and specifying the right COM port you should able to use also esptool.py.

Regards,
Fabrizio
