### ISSUE TITLE
Time menu behaves strangely

### ISSUE THREAD

**Issue by freeck** [fdivitto/ESPWebFramework#8]
Fabrizio,

First of all, great work! Nicely coded, and very stable so far.
The framework is an excellent starting point for my application. 
One minor issue: in case you enter a timezone value and save the value...time values displayed in the orange frame of the page seem to be incorrect. After rebooting the values are updated correctly.

Another issue: Password is displayed visable, could that be displayed as *******\* ?

Thanks so far!

**Comment by fdivitto** [comment]
Thank you for the tests!

Do you have a screenshot about the timezone settings problem?

Fabrizio

**Comment by freeck** [comment]
Unfortunately I cannot reproduce the phenomena I saw a few month ago, the test was then performed with another esp-module. So perhaps it was an hardware related issue (??). I have to say that my faith in the stability thus useability of the esp8266 modules is not so great anymore.

But I observe some behaviour in the application I do not understand: 
Client-mode: In case I select "client mode" I do not see the IP- and gateway-adres updated on the webpage of the esp-module, so I have no notion whether the client mode is working OK. So perhaps DHCP isnt working? Everything seems to work OK if I select static-IP; then I can access the module via AP- and client-mode.

Regards

**Comment by freeck** [comment]
Hello Fabrizio, 
Unfortunately I cannot reproduce the phenomena I saw a few month ago, the test was then performed with another esp-module. So perhaps it was an hardware related issue (??). I have to say that my faith in the stability thus useability of the esp8266 modules is not so great anymore. 

But I observe some behaviour in the application I do not understand: 
Client-mode: In case I select "client mode" I do not see the IP- and gateway-adres updated on the webpage of the esp-module, so I have no notion whether the client mode is working OK. So perhaps DHCP isnt working? Everything seems to work OK if I select static-IP; then I can access the module via AP- and client-mode.


Regards
Fred


Verstuurd vanaf mijn iPad
